/**
 * Master Role-Based Access Control (RBAC) Matrix
 * Sri Mayyia Caterers Enterprise ERP (Since 1953)
 */

export const MODULES = {
  DASHBOARD: 'dashboard',
  EVENT_BOOKING: 'event_booking',
  MENU_PLANNING: 'menu_planning',
  KITCHEN_EXECUTION: 'kitchen_execution',
  INHOUSE_INVENTORY: 'inhouse_inventory',
  LABOUR_MANAGEMENT: 'labour_management',
  VENDOR_MANAGEMENT: 'vendor_management',
  QUOTATION_BILLING: 'quotation_billing',
  REPORTS_ANALYTICS: 'reports_analytics',
  HISTORICAL_LEARNING: 'historical_learning',
  RBAC_ADMIN: 'rbac_admin'
};

export const MODULE_NAMES = {
  [MODULES.DASHBOARD]: 'Executive Dashboard',
  [MODULES.EVENT_BOOKING]: 'Event Booking & Scheduling',
  [MODULES.MENU_PLANNING]: 'Menu Planning & Archetypes',
  [MODULES.KITCHEN_EXECUTION]: 'Kitchen Execution Board',
  [MODULES.INHOUSE_INVENTORY]: 'Inhouse Storage & Inventory',
  [MODULES.LABOUR_MANAGEMENT]: 'Agency & Labour Management',
  [MODULES.VENDOR_MANAGEMENT]: 'Vendor Management & PO Dispatch',
  [MODULES.QUOTATION_BILLING]: 'Quotation, Markup & Billing',
  [MODULES.REPORTS_ANALYTICS]: 'Business Reports & Analytics',
  [MODULES.HISTORICAL_LEARNING]: 'Historical Learning Engine',
  [MODULES.RBAC_ADMIN]: 'Master Admin & Permissions'
};

export const ACCESS_LEVELS = {
  WRITE: 'write', // Full Create/Edit/Delete
  READ: 'read',   // View Only
  HIDE: 'hide'    // Tab Hidden & Access Blocked
};

export const DEFAULT_RBAC_MATRIX = {
  'Admin': {
    [MODULES.DASHBOARD]: ACCESS_LEVELS.WRITE,
    [MODULES.EVENT_BOOKING]: ACCESS_LEVELS.WRITE,
    [MODULES.MENU_PLANNING]: ACCESS_LEVELS.WRITE,
    [MODULES.KITCHEN_EXECUTION]: ACCESS_LEVELS.WRITE,
    [MODULES.INHOUSE_INVENTORY]: ACCESS_LEVELS.WRITE,
    [MODULES.LABOUR_MANAGEMENT]: ACCESS_LEVELS.WRITE,
    [MODULES.VENDOR_MANAGEMENT]: ACCESS_LEVELS.WRITE,
    [MODULES.QUOTATION_BILLING]: ACCESS_LEVELS.WRITE,
    [MODULES.REPORTS_ANALYTICS]: ACCESS_LEVELS.WRITE,
    [MODULES.HISTORICAL_LEARNING]: ACCESS_LEVELS.WRITE,
    [MODULES.RBAC_ADMIN]: ACCESS_LEVELS.WRITE
  },
  'Sales Executive': {
    [MODULES.DASHBOARD]: ACCESS_LEVELS.READ,
    [MODULES.EVENT_BOOKING]: ACCESS_LEVELS.WRITE,
    [MODULES.MENU_PLANNING]: ACCESS_LEVELS.WRITE,
    [MODULES.KITCHEN_EXECUTION]: ACCESS_LEVELS.HIDE,
    [MODULES.INHOUSE_INVENTORY]: ACCESS_LEVELS.HIDE,
    [MODULES.LABOUR_MANAGEMENT]: ACCESS_LEVELS.HIDE,
    [MODULES.VENDOR_MANAGEMENT]: ACCESS_LEVELS.HIDE,
    [MODULES.QUOTATION_BILLING]: ACCESS_LEVELS.WRITE,
    [MODULES.REPORTS_ANALYTICS]: ACCESS_LEVELS.READ,
    [MODULES.HISTORICAL_LEARNING]: ACCESS_LEVELS.READ,
    [MODULES.RBAC_ADMIN]: ACCESS_LEVELS.HIDE
  },
  'Chef': {
    [MODULES.DASHBOARD]: ACCESS_LEVELS.READ,
    [MODULES.EVENT_BOOKING]: ACCESS_LEVELS.READ,
    [MODULES.MENU_PLANNING]: ACCESS_LEVELS.WRITE,
    [MODULES.KITCHEN_EXECUTION]: ACCESS_LEVELS.WRITE,
    [MODULES.INHOUSE_INVENTORY]: ACCESS_LEVELS.READ,
    [MODULES.LABOUR_MANAGEMENT]: ACCESS_LEVELS.HIDE,
    [MODULES.VENDOR_MANAGEMENT]: ACCESS_LEVELS.READ,
    [MODULES.QUOTATION_BILLING]: ACCESS_LEVELS.HIDE,
    [MODULES.REPORTS_ANALYTICS]: ACCESS_LEVELS.HIDE,
    [MODULES.HISTORICAL_LEARNING]: ACCESS_LEVELS.READ,
    [MODULES.RBAC_ADMIN]: ACCESS_LEVELS.HIDE
  },
  'HR Manager': {
    [MODULES.DASHBOARD]: ACCESS_LEVELS.READ,
    [MODULES.EVENT_BOOKING]: ACCESS_LEVELS.READ,
    [MODULES.MENU_PLANNING]: ACCESS_LEVELS.READ,
    [MODULES.KITCHEN_EXECUTION]: ACCESS_LEVELS.READ,
    [MODULES.INHOUSE_INVENTORY]: ACCESS_LEVELS.HIDE,
    [MODULES.LABOUR_MANAGEMENT]: ACCESS_LEVELS.WRITE,
    [MODULES.VENDOR_MANAGEMENT]: ACCESS_LEVELS.READ,
    [MODULES.QUOTATION_BILLING]: ACCESS_LEVELS.HIDE,
    [MODULES.REPORTS_ANALYTICS]: ACCESS_LEVELS.READ,
    [MODULES.HISTORICAL_LEARNING]: ACCESS_LEVELS.HIDE,
    [MODULES.RBAC_ADMIN]: ACCESS_LEVELS.HIDE
  },
  'Store Incharge': {
    [MODULES.DASHBOARD]: ACCESS_LEVELS.READ,
    [MODULES.EVENT_BOOKING]: ACCESS_LEVELS.READ,
    [MODULES.MENU_PLANNING]: ACCESS_LEVELS.READ,
    [MODULES.KITCHEN_EXECUTION]: ACCESS_LEVELS.READ,
    [MODULES.INHOUSE_INVENTORY]: ACCESS_LEVELS.WRITE,
    [MODULES.LABOUR_MANAGEMENT]: ACCESS_LEVELS.HIDE,
    [MODULES.VENDOR_MANAGEMENT]: ACCESS_LEVELS.WRITE,
    [MODULES.QUOTATION_BILLING]: ACCESS_LEVELS.HIDE,
    [MODULES.REPORTS_ANALYTICS]: ACCESS_LEVELS.HIDE,
    [MODULES.HISTORICAL_LEARNING]: ACCESS_LEVELS.HIDE,
    [MODULES.RBAC_ADMIN]: ACCESS_LEVELS.HIDE
  },
  'Accountant': {
    [MODULES.DASHBOARD]: ACCESS_LEVELS.READ,
    [MODULES.EVENT_BOOKING]: ACCESS_LEVELS.READ,
    [MODULES.MENU_PLANNING]: ACCESS_LEVELS.HIDE,
    [MODULES.KITCHEN_EXECUTION]: ACCESS_LEVELS.HIDE,
    [MODULES.INHOUSE_INVENTORY]: ACCESS_LEVELS.READ,
    [MODULES.LABOUR_MANAGEMENT]: ACCESS_LEVELS.READ,
    [MODULES.VENDOR_MANAGEMENT]: ACCESS_LEVELS.READ,
    [MODULES.QUOTATION_BILLING]: ACCESS_LEVELS.WRITE,
    [MODULES.REPORTS_ANALYTICS]: ACCESS_LEVELS.WRITE,
    [MODULES.HISTORICAL_LEARNING]: ACCESS_LEVELS.READ,
    [MODULES.RBAC_ADMIN]: ACCESS_LEVELS.HIDE
  },
  'Agency': {
    [MODULES.DASHBOARD]: ACCESS_LEVELS.READ,
    [MODULES.EVENT_BOOKING]: ACCESS_LEVELS.READ,
    [MODULES.MENU_PLANNING]: ACCESS_LEVELS.HIDE,
    [MODULES.KITCHEN_EXECUTION]: ACCESS_LEVELS.READ,
    [MODULES.INHOUSE_INVENTORY]: ACCESS_LEVELS.HIDE,
    [MODULES.LABOUR_MANAGEMENT]: ACCESS_LEVELS.WRITE,
    [MODULES.VENDOR_MANAGEMENT]: ACCESS_LEVELS.HIDE,
    [MODULES.QUOTATION_BILLING]: ACCESS_LEVELS.HIDE,
    [MODULES.REPORTS_ANALYTICS]: ACCESS_LEVELS.HIDE,
    [MODULES.HISTORICAL_LEARNING]: ACCESS_LEVELS.HIDE,
    [MODULES.RBAC_ADMIN]: ACCESS_LEVELS.HIDE
  }
};

/**
 * Checks if a role has the required access level for a module
 */
export const checkPermission = (matrix, role, module, requiredLevel = ACCESS_LEVELS.READ) => {
  const rolePermissions = (matrix || DEFAULT_RBAC_MATRIX)[role] || {};
  const currentLevel = rolePermissions[module] || ACCESS_LEVELS.HIDE;

  if (requiredLevel === ACCESS_LEVELS.WRITE) {
    return currentLevel === ACCESS_LEVELS.WRITE;
  }
  if (requiredLevel === ACCESS_LEVELS.READ) {
    return currentLevel === ACCESS_LEVELS.READ || currentLevel === ACCESS_LEVELS.WRITE;
  }
  return currentLevel !== ACCESS_LEVELS.HIDE;
};
